name: Docker Build & Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    name: 🐳 Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Cambiar a true si configuras Docker Hub/GHCR
          tags: repobanner-pro:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max